# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Mon Aug 13 15:56:05 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(418, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Target_LineEdit = QtGui.QLineEdit(self.groupBox)
        self.Target_LineEdit.setEnabled(True)
        self.Target_LineEdit.setDragEnabled(True)
        self.Target_LineEdit.setReadOnly(True)
        self.Target_LineEdit.setObjectName(_fromUtf8("Target_LineEdit"))
        self.verticalLayout_2.addWidget(self.Target_LineEdit)
        self.Target_Button = QtGui.QPushButton(self.groupBox)
        self.Target_Button.setDefault(True)
        self.Target_Button.setFlat(False)
        self.Target_Button.setObjectName(_fromUtf8("Target_Button"))
        self.verticalLayout_2.addWidget(self.Target_Button)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.prefixedit = QtGui.QLineEdit(self.groupBox_2)
        self.prefixedit.setObjectName(_fromUtf8("prefixedit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixedit)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.Dimensions_Box = QtGui.QGroupBox(self.centralwidget)
        self.Dimensions_Box.setObjectName(_fromUtf8("Dimensions_Box"))
        self.formLayout = QtGui.QFormLayout(self.Dimensions_Box)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.Dimensions_Box)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.lsize = QtGui.QSpinBox(self.Dimensions_Box)
        self.lsize.setMaximum(9999)
        self.lsize.setProperty("value", 0)
        self.lsize.setObjectName(_fromUtf8("lsize"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lsize)
        self.label_2 = QtGui.QLabel(self.Dimensions_Box)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.msize = QtGui.QSpinBox(self.Dimensions_Box)
        self.msize.setMaximum(9999)
        self.msize.setProperty("value", 0)
        self.msize.setObjectName(_fromUtf8("msize"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.msize)
        self.label_3 = QtGui.QLabel(self.Dimensions_Box)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ssize = QtGui.QSpinBox(self.Dimensions_Box)
        self.ssize.setMaximum(9999)
        self.ssize.setProperty("value", 0)
        self.ssize.setObjectName(_fromUtf8("ssize"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ssize)
        self.verticalLayout.addWidget(self.Dimensions_Box)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(400, 200))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.Run_Button = QtGui.QPushButton(self.centralwidget)
        self.Run_Button.setObjectName(_fromUtf8("Run_Button"))
        self.verticalLayout.addWidget(self.Run_Button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "eCIP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Target Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.Target_LineEdit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Target location", None, QtGui.QApplication.UnicodeUTF8))
        self.Target_LineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "C:\\Users\\Edward\\Documents", None, QtGui.QApplication.UnicodeUTF8))
        self.Target_Button.setStatusTip(QtGui.QApplication.translate("MainWindow", "Navigate to your target folder...", None, QtGui.QApplication.UnicodeUTF8))
        self.Target_Button.setText(QtGui.QApplication.translate("MainWindow", "Select folder...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "File Naming", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixedit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "e.g. June or Hats", None, QtGui.QApplication.UnicodeUTF8))
        self.Dimensions_Box.setTitle(QtGui.QApplication.translate("MainWindow", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Large", None, QtGui.QApplication.UnicodeUTF8))
        self.lsize.setSuffix(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.msize.setSuffix(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Small", None, QtGui.QApplication.UnicodeUTF8))
        self.ssize.setSuffix(QtGui.QApplication.translate("MainWindow", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "eCommerce Image Processor v1.0\n"
"by Edward Knowles", None, QtGui.QApplication.UnicodeUTF8))
        self.Run_Button.setStatusTip(QtGui.QApplication.translate("MainWindow", "Click here to start the batch", None, QtGui.QApplication.UnicodeUTF8))
        self.Run_Button.setText(QtGui.QApplication.translate("MainWindow", "Start Process", None, QtGui.QApplication.UnicodeUTF8))

